version: '3'
services:
    database:
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=super_admin
            - POSTGRES_PASSWORD=SomeSecretPassword
            - POSTGRES_DB=coffee-app
        ports:
            - 5432:5432

    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4001:4001
            - 4002:4002
            - 4003:4003
        depends_on:
            - database
        environment:
            - DB_HOST=database
            - DB_USER=super_admin
            - DB_PASSWORD=SomeSecretPassword
            - DB_NAME=coffee-app
        scale: 3

    load_balancer:
        build:
            context: .
            dockerfile: Dockerfile-load-balancer
        ports:
            - 4000:4000
        depends_on:
            - api
