version: '3'
services:
    mysql_db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            - MYSQL_ROOT_PASSWORD=coffee-app
            - MYSQL_DATABASE=coffee-app
            - MYSQL_USER=coffee-app
            - MYSQL_PASSWORD=coffee-app
        ports:
            - 3307:3307
        volumes:
            - ./mysql_db_data:/var/lib/mysql

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        ports:
            - 4001:4444
            - 4002:4444
            - 4003:4444
        depends_on:
            - mysql_db
        environment:
            - DB_HOST=localhost
            - DB_USER=coffee-app
            - DB_PASSWORD=coffee-app
            - DB_NAME=coffee-app

    load_balancer:
        build:
            context: .
            dockerfile: Dockerfile-load-balancer
        container_name: load_balancer
        ports:
            - 4000:4000
        environment:
            - HOSTS=http://localhost:4001,http://localhost:4002,http://localhost:4003
        depends_on:
            - api
