version: '3'
services:
    mysql_db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            - MYSQL_ROOT_PASSWORD=coffeeapp
            - MYSQL_DATABASE=coffeeapp
            - MYSQL_USER=coffeeapp
            - MYSQL_PASSWORD=coffeeapp
        ports:
            - 3306:3306
        volumes:
            - ./mysql_db_data:/var/lib/mysql

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        ports:
            - 4001:4444
            - 4002:4444
            - 4003:4444
        depends_on:
            - mysql_db
        environment:
            - DB_HOST=localhost
            - DB_USER=coffeeapp
            - DB_PASSWORD=coffeeapp

    load_balancer:
        build:
            context: .
            dockerfile: Dockerfile-load-balancer
        container_name: load_balancer
        ports:
            - 4000:4000
        environment:
            - HOSTS=$HOSTS
        depends_on:
            - api
