name: CoffeeApp Build Pipeline

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Check node version
              run: node -v

            - name: Install dependencies
              run: npm install

            - name: Test application
              run: node --test

            - name: Set up SSH key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.VM_KEY }}

            - name: Run SSH command on production VM
              uses: appleboy/ssh-action@master
              with:
                  host: 3.70.216.70
                  username: ubuntu
                  key: ${{ secrets.VM_KEY }}
                  script: |
                      cd coffee-app
                      sudo npm install pm2 -g
                      sudo git pull
                      sudo npm install
                      sudo pm2 stop all
                      sudo pm2 start -f load-balancer.js
                      sudo pm2 start -f index.js -- 4001
                      sudo pm2 start -f index.js -- 4002
                      sudo pm2 start -f index.js -- 4003
                      sudo pm2 start -f index.js -- 4004
                      sudo pm2 start -f index.js -- 4005
                      sudo pm2 save
                      sudo pm2 startup

            - name: Sleep three seconds
              run: sleep 3s

            - name: Healthcheck for load balancer
              run: curl --silent http://3.70.216.70/load-balancer-health-check

            - name: API Healthcheck
              run: curl --silent http://3.70.216.70/
